image:
  tag: 0.1
  repository: "gcr.io/heptio-images/ks-guestbook-demo"
  pullPolicy: "IfNotPresent"
ingress:
  path: "/"
  hosts:
  - "chart-example.local"
  annotations: {}
  tls: []
  enabled: false
replicaCount: 2
tolerations: []
service:
  port: 80
  type: "ClusterIP"
containerPort: 80
resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "128Mi"
    cpu: "100m"
nodeSelector: {}
affinity: {}
