apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: squid
  name: squid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: squid
  template:
    metadata:
      labels:
        app: squid
    spec:
      containers:
        - name: squid
          image: ubuntu/squid:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "512Mi"
              cpu: "0.5"
            limits:
              memory: "512Mi"
              cpu: "0.5"
          env:
            - name: SQUID_CACHE_SIZE
              value: "70000"
            - name: SQUID_CACHE_MEM
              value: "2048"
          ports:
            - containerPort: 3128
              protocol: TCP
          volumeMounts:
            - mountPath: /var/cache/squid
              name: squid-cache
            - mountPath: /var/log/squid
              name: squid-log
            - mountPath: /etc/squid/squid.conf
              name: squid-conf
              subPath: squid.conf
          livenessProbe:
            tcpSocket:
              port: 3128
            initialDelaySeconds: 40
            timeoutSeconds: 4
      volumes:
        - name: squid-cache
          emptyDir: {}
        - name: squid-log
          emptyDir: {}
        - name: squid-conf
          configMap:
            name: squid-conf
            items:
              - key: squid.conf
                path: squid.conf
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: squid-conf
data:
  squid.conf: |
    acl SSL_ports port 443

    http_access deny !Safe_ports

    http_access deny CONNECT !SSL_ports

    http_access allow localhost manager
    http_access deny manager

    http_access allow localhost

    http_access deny to_localhost

    http_access deny to_linklocal

    include /etc/squid/conf.d/*.conf

    http_access deny all

    coredump_dir /var/spool/squid

    refresh_pattern ^ftp:		1440	20%	10080
    refresh_pattern -i (/cgi-bin/|\?) 0	0%	0
    refresh_pattern \/(Packages|Sources)(|\.bz2|\.gz|\.xz)$ 0 0% 0 refresh-ims
    refresh_pattern \/Release(|\.gpg)$ 0 0% 0 refresh-ims
    refresh_pattern \/InRelease$ 0 0% 0 refresh-ims
    refresh_pattern \/(Translation-.*)(|\.bz2|\.gz|\.xz)$ 0 0% 0 refresh-ims
    refresh_pattern .		0	20%	4320
