apiVersion: apps/v1
kind: Deployment
metadata:
  name: third-simple-flask
  labels:
    app: third-simple-flask
spec:
  replicas: 2
  minReadySeconds: 15
  selector:
    matchLabels:
      app: third-simple-flask
  template:
    metadata:
      labels:
        app: third-simple-flask
    spec:
      containers:
        - name: flask-container
          image: austinthao/flask-app:v1
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15   # Wait 15 seconds before starting to probe
            periodSeconds: 5          # Check every 2 seconds after that
            timeoutSeconds: 1         # Timeout for each probe
            failureThreshold: 3       # Mark pod not ready after 3 consecutive failures
            successThreshold: 1       # Mark pod ready after 1 successful probe
          ports:
            - containerPort: 80
